FUNCTION MAP2I_NREL_TO_WOREL .
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(ZZDD_BAPI_NETWORK_RELATION)
*"  LIKE  ZZDD_BAPI_NETWORK_RELATION
*"  STRUCTURE  ZZDD_BAPI_NETWORK_RELATION
*"  CHANGING
*"     REFERENCE(ZBAOR) LIKE  ZBAOR STRUCTURE  ZBAOR
*"  EXCEPTIONS
*"      ERROR_CONVERTING_ISO_CODE
*"--------------------------------------------------------------------

* This function module was generated. Don't change it manually!
* <VERSION>|4
* <BAPI_STRUCTURE>|ZZDD_BAPI_NETWORK_RELATION
* <SAP_STRUCTURE>|ZBAOR
* <INTERN_TO_EXTERN>|
* <APPEND FORM>|

* <BAPI_FIELD>|NETWORK_PREDECESSOR
* <SAP_FIELD>|ORDER_PREDECESSOR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE ZZDD_BAPI_NETWORK_RELATION-NETWORK_PREDECESSOR
  TO ZBAOR-ORDER_PREDECESSOR                                      .

* <BAPI_FIELD>|ACTIVITY_PREDECESSOR
* <SAP_FIELD>|OPERATION_PREDECESSOR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE ZZDD_BAPI_NETWORK_RELATION-ACTIVITY_PREDECESSOR
  TO ZBAOR-OPERATION_PREDECESSOR                                  .

* <BAPI_FIELD>|NETWORK_SUCCESSOR
* <SAP_FIELD>|ORDER_SUCCESSOR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE ZZDD_BAPI_NETWORK_RELATION-NETWORK_SUCCESSOR
  TO ZBAOR-ORDER_SUCCESSOR                                        .

* <BAPI_FIELD>|ACTIVITY_SUCCESSOR
* <SAP_FIELD>|OPERATION_SUCCESSOR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE ZZDD_BAPI_NETWORK_RELATION-ACTIVITY_SUCCESSOR
  TO ZBAOR-OPERATION_SUCCESSOR                                    .

* <BAPI_FIELD>|RELATION_TYPE
* <SAP_FIELD>|RELATION_TYPE
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE ZZDD_BAPI_NETWORK_RELATION-RELATION_TYPE
  TO ZBAOR-RELATION_TYPE                                          .

* <BAPI_FIELD>|DURATION_RELATION
* <SAP_FIELD>|DURATION_RELATION
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE ZZDD_BAPI_NETWORK_RELATION-DURATION_RELATION
  TO ZBAOR-DURATION_RELATION                                      .

* <BAPI_FIELD>|FACTORY_CALENDAR
* <SAP_FIELD>|FACTORY_CALENDAR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE ZZDD_BAPI_NETWORK_RELATION-FACTORY_CALENDAR
  TO ZBAOR-FACTORY_CALENDAR                                       .

* <BAPI_FIELD>|PERCENT_OF_SUC_PR
* <SAP_FIELD>|PERCENT_OF_SUCCESSOR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE ZZDD_BAPI_NETWORK_RELATION-PERCENT_OF_SUC_PR
  TO ZBAOR-PERCENT_OF_SUCCESSOR                                   .

* <BAPI_FIELD>|DURATION_KEY
* <SAP_FIELD>|DURATION_KEY
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE ZZDD_BAPI_NETWORK_RELATION-DURATION_KEY
  TO ZBAOR-DURATION_KEY                                           .

* <BAPI_FIELD>|WORK_CNTR
* <SAP_FIELD>|WORK_CNTR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE ZZDD_BAPI_NETWORK_RELATION-WORK_CNTR
  TO ZBAOR-WORK_CNTR                                              .

* <BAPI_FIELD>|PLANT
* <SAP_FIELD>|PLANT
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE ZZDD_BAPI_NETWORK_RELATION-PLANT
  TO ZBAOR-PLANT                                                  .

* <BAPI_FIELD>|DURATION_RELATION_UNIT_ISO
* <SAP_FIELD>|DURATION_RELATION_UNIT
* <CODE_PART>|ISO_INT_UNIT
* <ADD_FIELD>|DURATION_RELATION_UNIT
IF NOT ZZDD_BAPI_NETWORK_RELATION-DURATION_RELATION_UNIT
IS INITIAL.
  MOVE ZZDD_BAPI_NETWORK_RELATION-DURATION_RELATION_UNIT
    TO ZBAOR-DURATION_RELATION_UNIT                                 .
ELSEIF ZZDD_BAPI_NETWORK_RELATION-DURATION_RELATION_UNIT_ISO
IS INITIAL.
  CLEAR ZBAOR-DURATION_RELATION_UNIT                                 .
ELSE.
  CALL FUNCTION 'UNIT_OF_MEASURE_ISO_TO_SAP'
       EXPORTING
            ISO_CODE  =
       ZZDD_BAPI_NETWORK_RELATION-DURATION_RELATION_UNIT_ISO
       IMPORTING
            SAP_CODE  =
       ZBAOR-DURATION_RELATION_UNIT
       EXCEPTIONS
            NOT_FOUND = 1
            OTHERS    = 2.
  IF SY-SUBRC <> 0.
    MESSAGE A548(B1) WITH
    ZZDD_BAPI_NETWORK_RELATION-DURATION_RELATION_UNIT_ISO
    'DURATION_RELATION_UNIT_ISO    '
    RAISING ERROR_CONVERTING_ISO_CODE.
  ENDIF.
ENDIF.





ENDFUNCTION.
