FUNCTION MAP2I_IBAPI_HEADER_OUT_TO_BAPI.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IBAPI_HEADER_OUT) LIKE  IBAPI_HEADER_OUT
*"  STRUCTURE  IBAPI_HEADER_OUT
*"  CHANGING
*"     REFERENCE(BAPI_NETWORK_EXP) LIKE  BAPI_NETWORK_EXP
*"  STRUCTURE  BAPI_NETWORK_EXP
*"  EXCEPTIONS
*"      ERROR_CONVERTING_ISO_CODE
*"--------------------------------------------------------------------

* This function module was generated. Don't change it manually!
* <VERSION>|4
* <BAPI_STRUCTURE>|IBAPI_HEADER_OUT
* <SAP_STRUCTURE>|BAPI_NETWORK_EXP
* <INTERN_TO_EXTERN>|
* <APPEND FORM>|X

* <BAPI_FIELD>|ORDERID
* <SAP_FIELD>|NETWORK
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-ORDERID
  TO BAPI_NETWORK_EXP-NETWORK                                     .

* <BAPI_FIELD>|ORDER_TYPE
* <SAP_FIELD>|NETWORK_TYPE
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-ORDER_TYPE
  TO BAPI_NETWORK_EXP-NETWORK_TYPE                                .

* <BAPI_FIELD>|PLANPLANT
* <SAP_FIELD>|PLANT
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-PLANPLANT
  TO BAPI_NETWORK_EXP-PLANT                                       .

* <BAPI_FIELD>|PLANT
* <SAP_FIELD>|PLANT
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-PLANT
  TO BAPI_NETWORK_EXP-PLANT                                       .

* <BAPI_FIELD>|PROFIT_CTR
* <SAP_FIELD>|PROFIT_CTR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-PROFIT_CTR
  TO BAPI_NETWORK_EXP-PROFIT_CTR                                  .

* <BAPI_FIELD>|FUNC_AREA
* <SAP_FIELD>|FUNC_AREA_LONG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-FUNC_AREA
  TO BAPI_NETWORK_EXP-FUNC_AREA_LONG                              .

* <BAPI_FIELD>|TAXJURCODE
* <SAP_FIELD>|TAXJURCODE
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-TAXJURCODE
  TO BAPI_NETWORK_EXP-TAXJURCODE                                  .

* <BAPI_FIELD>|START_DATE
* <SAP_FIELD>|START_DATE
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-START_DATE
  TO BAPI_NETWORK_EXP-START_DATE                                  .

* <BAPI_FIELD>|FINISH_DATE
* <SAP_FIELD>|FINISH_DATE
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-FINISH_DATE
  TO BAPI_NETWORK_EXP-FINISH_DATE                                 .

* <BAPI_FIELD>|SCHED_TYPE
* <SAP_FIELD>|SCHED_TYPE
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-SCHED_TYPE
  TO BAPI_NETWORK_EXP-SCHED_TYPE                                  .

* <BAPI_FIELD>|PRODUCTION_START_DATE
* <SAP_FIELD>|SCHED_START_DATE
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-PRODUCTION_START_DATE
  TO BAPI_NETWORK_EXP-SCHED_START_DATE                            .

* <BAPI_FIELD>|PRODUCTION_FINISH_DATE
* <SAP_FIELD>|SCHED_FINISH_DATE
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-PRODUCTION_FINISH_DATE
  TO BAPI_NETWORK_EXP-SCHED_FINISH_DATE                           .

* <BAPI_FIELD>|ACTUAL_START_DATE
* <SAP_FIELD>|ACTUAL_START_DATE
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-ACTUAL_START_DATE
  TO BAPI_NETWORK_EXP-ACTUAL_START_DATE                           .

* <BAPI_FIELD>|ACTUAL_FINISH_DATE
* <SAP_FIELD>|CONFIRMED_FINISH_DATE
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-ACTUAL_FINISH_DATE
  TO BAPI_NETWORK_EXP-CONFIRMED_FINISH_DATE                       .

* <BAPI_FIELD>|NETWORK_PROFILE
* <SAP_FIELD>|PROFILE
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-NETWORK_PROFILE
  TO BAPI_NETWORK_EXP-PROFILE                                     .

* <BAPI_FIELD>|SHORT_TEXT
* <SAP_FIELD>|SHORT_TEXT
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE IBAPI_HEADER_OUT-SHORT_TEXT
  TO BAPI_NETWORK_EXP-SHORT_TEXT                                  .

* <BAPI_FIELD>|CURRENCY_ISO
* <SAP_FIELD>|CONTROLLING_AREA_CURRENCY
* <CODE_PART>|ISO_INT_CURR
* <ADD_FIELD>|CURRENCY
IF NOT IBAPI_HEADER_OUT-CURRENCY
IS INITIAL.
  MOVE IBAPI_HEADER_OUT-CURRENCY
    TO BAPI_NETWORK_EXP-CONTROLLING_AREA_CURRENCY                   .
ELSEIF IBAPI_HEADER_OUT-CURRENCY_ISO
IS INITIAL.
  CLEAR BAPI_NETWORK_EXP-CONTROLLING_AREA_CURRENCY                   .
ELSE.
  CALL FUNCTION 'CURRENCY_CODE_ISO_TO_SAP'
       EXPORTING
            ISO_CODE  =
       IBAPI_HEADER_OUT-CURRENCY_ISO
       IMPORTING
            SAP_CODE  =
       BAPI_NETWORK_EXP-CONTROLLING_AREA_CURRENCY
       EXCEPTIONS
            NOT_FOUND = 1
            OTHERS    = 2.
  IF SY-SUBRC <> 0.
    MESSAGE A547(B1) WITH
    IBAPI_HEADER_OUT-CURRENCY_ISO
    'CURRENCY_ISO                  '
    RAISING ERROR_CONVERTING_ISO_CODE.
  ENDIF.
ENDIF.

PERFORM MAP2I_IBAPI_HEADER_OUT_TO_BAPI
  USING
    IBAPI_HEADER_OUT
  CHANGING
    BAPI_NETWORK_EXP              .





ENDFUNCTION.

FORM MAP2I_IBAPI_HEADER_OUT_TO_BAPI
  USING
    IBAPI_HEADER_OUT
    STRUCTURE IBAPI_HEADER_OUT
  CHANGING
    BAPI_NETWORK_EXP
    STRUCTURE BAPI_NETWORK_EXP              .

ENDFORM.
