FUNCTION MAP2I_BAPI_ALM_ORDER_COMPONENT.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(BAPI_ALM_ORDER_COMPONENT_E)
*"  LIKE  BAPI_ALM_ORDER_COMPONENT_E
*"  STRUCTURE  BAPI_ALM_ORDER_COMPONENT_E
*"  CHANGING
*"     REFERENCE(RESBD) LIKE  RESBD STRUCTURE  RESBD
*"  EXCEPTIONS
*"      ERROR_CONVERTING_ISO_CODE
*"--------------------------------------------------------------------

* This function module was generated. Don't change it manually!
* <VERSION>|4
* <BAPI_STRUCTURE>|BAPI_ALM_ORDER_COMPONENT_E
* <SAP_STRUCTURE>|RESBD
* <INTERN_TO_EXTERN>|
* <APPEND FORM>|X

* <BAPI_FIELD>|PREQ_NAME
* <SAP_FIELD>|AFNAM
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-PREQ_NAME
  TO RESBD-AFNAM                                                  .

* <BAPI_FIELD>|TRACKINGNO
* <SAP_FIELD>|BEDNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-TRACKINGNO
  TO RESBD-BEDNR                                                  .

* <BAPI_FIELD>|PURCH_ORG
* <SAP_FIELD>|EKORG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-PURCH_ORG
  TO RESBD-EKORG                                                  .

* <BAPI_FIELD>|MATL_DESC
* <SAP_FIELD>|MATXT
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-MATL_DESC
  TO RESBD-MATXT                                                  .

* <BAPI_FIELD>|REQUIREMENT_QUANTITY
* <SAP_FIELD>|MENGE
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-REQUIREMENT_QUANTITY
  TO RESBD-MENGE                                                  .

* <BAPI_FIELD>|AGREEMENT
* <SAP_FIELD>|KONNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-AGREEMENT
  TO RESBD-KONNR                                                  .

* <BAPI_FIELD>|AGMT_ITEM
* <SAP_FIELD>|KTPNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-AGMT_ITEM
  TO RESBD-KTPNR                                                  .

* <BAPI_FIELD>|RELATIONSHIP_TYPE
* <SAP_FIELD>|AOBAR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-RELATIONSHIP_TYPE
  TO RESBD-AOBAR                                                  .

* <BAPI_FIELD>|RELATIONSHIP_INTERVAL
* <SAP_FIELD>|DAUER
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-RELATIONSHIP_INTERVAL
  TO RESBD-DAUER                                                  .

* <BAPI_FIELD>|MRP_RELEVANT
* <SAP_FIELD>|AUDISP
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-MRP_RELEVANT
  TO RESBD-AUDISP                                                 .

* <BAPI_FIELD>|DIR_PROCUR
* <SAP_FIELD>|DBSKZ_D
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-DIR_PROCUR
  TO RESBD-DBSKZ_D                                                .

* <BAPI_FIELD>|SPECIAL_STOCK
* <SAP_FIELD>|SOBKZ_D
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-SPECIAL_STOCK
  TO RESBD-SOBKZ_D                                                .

* <BAPI_FIELD>|VSI_SIZE1
* <SAP_FIELD>|ROMS1
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-VSI_SIZE1
  TO RESBD-ROMS1                                                  .

* <BAPI_FIELD>|VSI_FORMULA
* <SAP_FIELD>|RFORM
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-VSI_FORMULA
  TO RESBD-RFORM                                                  .

* <BAPI_FIELD>|VSI_SIZE2
* <SAP_FIELD>|ROMS2
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-VSI_SIZE2
  TO RESBD-ROMS2                                                  .

* <BAPI_FIELD>|VSI_NO
* <SAP_FIELD>|ROANZ
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-VSI_NO
  TO RESBD-ROANZ                                                  .

* <BAPI_FIELD>|VSI_SIZE3
* <SAP_FIELD>|ROMS3
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-VSI_SIZE3
  TO RESBD-ROMS3                                                  .

* <BAPI_FIELD>|VSI_QTY
* <SAP_FIELD>|ROMEN
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-VSI_QTY
  TO RESBD-ROMEN                                                  .

* <BAPI_FIELD>|DISCONTINUATION
* <SAP_FIELD>|KZAUS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-DISCONTINUATION
  TO RESBD-KZAUS                                                  .

* <BAPI_FIELD>|ALT_ITEM
* <SAP_FIELD>|ALPOS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-ALT_ITEM
  TO RESBD-ALPOS                                                  .

* <BAPI_FIELD>|DELETE_IND
* <SAP_FIELD>|XLOEK
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-DELETE_IND
  TO RESBD-XLOEK                                                  .

* <BAPI_FIELD>|ORDERID
* <SAP_FIELD>|AUFNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-ORDERID
  TO RESBD-AUFNR                                                  .

* <BAPI_FIELD>|REQ_DATE
* <SAP_FIELD>|BDTER
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-REQ_DATE
  TO RESBD-BDTER                                                  .

* <BAPI_FIELD>|REQ_TIME
* <SAP_FIELD>|BDZTP
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-REQ_TIME
  TO RESBD-BDZTP                                                  .

* <BAPI_FIELD>|MOVE_TYPE
* <SAP_FIELD>|BWART
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-MOVE_TYPE
  TO RESBD-BWART                                                  .

* <BAPI_FIELD>|COMMITED_QUAN
* <SAP_FIELD>|DVMENG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-COMMITED_QUAN
  TO RESBD-DVMENG                                                 .

* <BAPI_FIELD>|PREQ_NO
* <SAP_FIELD>|BANFN
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-PREQ_NO
  TO RESBD-BANFN                                                  .

* <BAPI_FIELD>|PREQ_ITEM
* <SAP_FIELD>|BNFPO
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-PREQ_ITEM
  TO RESBD-BNFPO                                                  .

* <BAPI_FIELD>|DELIV_QTY
* <SAP_FIELD>|WEMNG_CMP
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-DELIV_QTY
  TO RESBD-WEMNG_CMP                                              .

* <BAPI_FIELD>|PURCHASE_ORDER_EXISTS
* <SAP_FIELD>|FLG_PURS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-PURCHASE_ORDER_EXISTS
  TO RESBD-FLG_PURS                                               .

* <BAPI_FIELD>|BASE_QTY
* <SAP_FIELD>|BMENGE
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-BASE_QTY
  TO RESBD-BMENGE                                                 .

* <BAPI_FIELD>|ACCTASSCAT
* <SAP_FIELD>|KNTTP
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-ACCTASSCAT
  TO RESBD-KNTTP                                                  .

* <BAPI_FIELD>|VALUATION_SPEC_STOCK
* <SAP_FIELD>|KZBWS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-VALUATION_SPEC_STOCK
  TO RESBD-KZBWS                                                  .

* <BAPI_FIELD>|CONSUMPT
* <SAP_FIELD>|KZVBR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-CONSUMPT
  TO RESBD-KZVBR                                                  .

* <BAPI_FIELD>|VENDOR_MAT
* <SAP_FIELD>|IDNLF
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-VENDOR_MAT
  TO RESBD-IDNLF                                                  .

* <BAPI_FIELD>|VSI_ORIGINAL_QTY
* <SAP_FIELD>|RNOMNG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-VSI_ORIGINAL_QTY
  TO RESBD-RNOMNG                                                 .

* <BAPI_FIELD>|MANUAL_REQUIREMENTS_DATE
* <SAP_FIELD>|KZMPF
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-MANUAL_REQUIREMENTS_DATE
  TO RESBD-KZMPF                                                  .

* <BAPI_FIELD>|LEAD_TIME_OFFSET_OPR
* <SAP_FIELD>|NLFZV
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-LEAD_TIME_OFFSET_OPR
  TO RESBD-NLFZV                                                  .

* <BAPI_FIELD>|RESERV_NO
* <SAP_FIELD>|RSNUM
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-RESERV_NO
  TO RESBD-RSNUM                                                  .

* <BAPI_FIELD>|RES_ITEM
* <SAP_FIELD>|RSPOS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-RES_ITEM
  TO RESBD-RSPOS                                                  .

* <BAPI_FIELD>|RES_TYPE
* <SAP_FIELD>|RSART
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-RES_TYPE
  TO RESBD-RSART                                                  .

* <BAPI_FIELD>|MOVEMENT
* <SAP_FIELD>|XWAOK
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-MOVEMENT
  TO RESBD-XWAOK                                                  .

* <BAPI_FIELD>|WITHDRAWN
* <SAP_FIELD>|KZEAR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-WITHDRAWN
  TO RESBD-KZEAR                                                  .

* <BAPI_FIELD>|MATERIAL
* <SAP_FIELD>|MATNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-MATERIAL
  TO RESBD-MATNR                                                  .

* <BAPI_FIELD>|PLANT
* <SAP_FIELD>|WERKS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-PLANT
  TO RESBD-WERKS                                                  .

* <BAPI_FIELD>|STGE_LOC
* <SAP_FIELD>|LGORT
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-STGE_LOC
  TO RESBD-LGORT                                                  .

* <BAPI_FIELD>|BATCH
* <SAP_FIELD>|CHARG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-BATCH
  TO RESBD-CHARG                                                  .

* <BAPI_FIELD>|FIXED_QUAN
* <SAP_FIELD>|FMENG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-FIXED_QUAN
  TO RESBD-FMENG                                                  .

* <BAPI_FIELD>|WITHD_QUAN
* <SAP_FIELD>|ENMNG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-WITHD_QUAN
  TO RESBD-ENMNG                                                  .

* <BAPI_FIELD>|SALES_ORD
* <SAP_FIELD>|KDAUF
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-SALES_ORD
  TO RESBD-KDAUF                                                  .

* <BAPI_FIELD>|S_ORD_ITEM
* <SAP_FIELD>|KDPOS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-S_ORD_ITEM
  TO RESBD-KDPOS                                                  .

* <BAPI_FIELD>|GL_ACCOUNT
* <SAP_FIELD>|SAKNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-GL_ACCOUNT
  TO RESBD-SAKNR                                                  .

* <BAPI_FIELD>|ORIGINAL_QTY
* <SAP_FIELD>|NOMNG
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-ORIGINAL_QTY
  TO RESBD-NOMNG                                                  .

* <BAPI_FIELD>|ITEM_CAT
* <SAP_FIELD>|POSTP
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-ITEM_CAT
  TO RESBD-POSTP                                                  .

* <BAPI_FIELD>|ITEM_NUMBER
* <SAP_FIELD>|POSNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-ITEM_NUMBER
  TO RESBD-POSNR                                                  .

* <BAPI_FIELD>|ITEM_TEXT1
* <SAP_FIELD>|POTX1
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-ITEM_TEXT1
  TO RESBD-POTX1                                                  .

* <BAPI_FIELD>|COST_RELEVANT
* <SAP_FIELD>|SANKA
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-COST_RELEVANT
  TO RESBD-SANKA                                                  .

* <BAPI_FIELD>|USAGE_PROB
* <SAP_FIELD>|EWAHR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-USAGE_PROB
  TO RESBD-EWAHR                                                  .

* <BAPI_FIELD>|SORT_STRING
* <SAP_FIELD>|SORTF
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-SORT_STRING
  TO RESBD-SORTF                                                  .

* <BAPI_FIELD>|BULK_MAT
* <SAP_FIELD>|SCHGT
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-BULK_MAT
  TO RESBD-SCHGT                                                  .

* <BAPI_FIELD>|MAT_PROVISION
* <SAP_FIELD>|BEIKZ
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-MAT_PROVISION
  TO RESBD-BEIKZ                                                  .

* <BAPI_FIELD>|INFO_REC
* <SAP_FIELD>|INFNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-INFO_REC
  TO RESBD-INFNR                                                  .

* <BAPI_FIELD>|WBS_ELEM
* <SAP_FIELD>|PSPEL
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-WBS_ELEM
  TO RESBD-PSPEL                                                  .

* <BAPI_FIELD>|ACTIVITY
* <SAP_FIELD>|VORNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-ACTIVITY
  TO RESBD-VORNR                                                  .

* <BAPI_FIELD>|PRICE
* <SAP_FIELD>|GPREIS
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-PRICE
  TO RESBD-GPREIS                                                 .

* <BAPI_FIELD>|PRICE_UNIT
* <SAP_FIELD>|PEINH
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-PRICE_UNIT
  TO RESBD-PEINH                                                  .

* <BAPI_FIELD>|BACKFLUSH
* <SAP_FIELD>|RGEKZ
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-BACKFLUSH
  TO RESBD-RGEKZ                                                  .

* <BAPI_FIELD>|VENDOR_NO
* <SAP_FIELD>|LIFNR
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-VENDOR_NO
  TO RESBD-LIFNR                                                  .

* <BAPI_FIELD>|PUR_GROUP
* <SAP_FIELD>|EKGRP
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-PUR_GROUP
  TO RESBD-EKGRP                                                  .

* <BAPI_FIELD>|DELIVERY_DAYS
* <SAP_FIELD>|LIFZT
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-DELIVERY_DAYS
  TO RESBD-LIFZT                                                  .

* <BAPI_FIELD>|GR_RCPT
* <SAP_FIELD>|WEMPF
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-GR_RCPT
  TO RESBD-WEMPF                                                  .

* <BAPI_FIELD>|GR_PR_TIME
* <SAP_FIELD>|WEBAZ
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-GR_PR_TIME
  TO RESBD-WEBAZ                                                  .

* <BAPI_FIELD>|MATL_GROUP
* <SAP_FIELD>|MATKL
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-MATL_GROUP
  TO RESBD-MATKL                                                  .

* <BAPI_FIELD>|UNLOAD_PT
* <SAP_FIELD>|ABLAD
* <CODE_PART>|A_MOVE
* <ADD_FIELD>|
MOVE BAPI_ALM_ORDER_COMPONENT_E-UNLOAD_PT
  TO RESBD-ABLAD                                                  .

* <BAPI_FIELD>|CURRENCY_ISO
* <SAP_FIELD>|WAERS
* <CODE_PART>|ISO_INT_CURR
* <ADD_FIELD>|CURRENCY
IF NOT BAPI_ALM_ORDER_COMPONENT_E-CURRENCY
IS INITIAL.
  MOVE BAPI_ALM_ORDER_COMPONENT_E-CURRENCY
    TO RESBD-WAERS                                                  .
ELSEIF BAPI_ALM_ORDER_COMPONENT_E-CURRENCY_ISO
IS INITIAL.
  CLEAR RESBD-WAERS                                                  .
ELSE.
  CALL FUNCTION 'CURRENCY_CODE_ISO_TO_SAP'
       EXPORTING
            ISO_CODE  =
       BAPI_ALM_ORDER_COMPONENT_E-CURRENCY_ISO
       IMPORTING
            SAP_CODE  =
       RESBD-WAERS
       EXCEPTIONS
            NOT_FOUND = 1
            OTHERS    = 2.
  IF SY-SUBRC <> 0.
    MESSAGE A547(B1) WITH
    BAPI_ALM_ORDER_COMPONENT_E-CURRENCY_ISO
    'CURRENCY_ISO                  '
    RAISING ERROR_CONVERTING_ISO_CODE.
  ENDIF.
ENDIF.

* <BAPI_FIELD>|LEAD_TIME_OFFSET_OPR_UNIT_ISO
* <SAP_FIELD>|NLFMV
* <CODE_PART>|ISO_INT_UNIT
* <ADD_FIELD>|LEAD_TIME_OFFSET_OPR_UNIT
IF NOT BAPI_ALM_ORDER_COMPONENT_E-LEAD_TIME_OFFSET_OPR_UNIT
IS INITIAL.
  MOVE BAPI_ALM_ORDER_COMPONENT_E-LEAD_TIME_OFFSET_OPR_UNIT
    TO RESBD-NLFMV                                                  .
ELSEIF BAPI_ALM_ORDER_COMPONENT_E-LEAD_TIME_OFFSET_OPR_UNIT_ISO
IS INITIAL.
  CLEAR RESBD-NLFMV                                                  .
ELSE.
  CALL FUNCTION 'UNIT_OF_MEASURE_ISO_TO_SAP'
       EXPORTING
            ISO_CODE  =
       BAPI_ALM_ORDER_COMPONENT_E-LEAD_TIME_OFFSET_OPR_UNIT_ISO
       IMPORTING
            SAP_CODE  =
       RESBD-NLFMV
       EXCEPTIONS
            NOT_FOUND = 1
            OTHERS    = 2.
  IF SY-SUBRC <> 0.
    MESSAGE A548(B1) WITH
    BAPI_ALM_ORDER_COMPONENT_E-LEAD_TIME_OFFSET_OPR_UNIT_ISO
    'LEAD_TIME_OFFSET_OPR_UNIT_ISO '
    RAISING ERROR_CONVERTING_ISO_CODE.
  ENDIF.
ENDIF.

* <BAPI_FIELD>|BASE_UOM_ISO
* <SAP_FIELD>|EINHEIT
* <CODE_PART>|ISO_INT_UNIT
* <ADD_FIELD>|BASE_UOM
IF NOT BAPI_ALM_ORDER_COMPONENT_E-BASE_UOM
IS INITIAL.
  MOVE BAPI_ALM_ORDER_COMPONENT_E-BASE_UOM
    TO RESBD-EINHEIT                                                .
ELSEIF BAPI_ALM_ORDER_COMPONENT_E-BASE_UOM_ISO
IS INITIAL.
  CLEAR RESBD-EINHEIT                                                .
ELSE.
  CALL FUNCTION 'UNIT_OF_MEASURE_ISO_TO_SAP'
       EXPORTING
            ISO_CODE  =
       BAPI_ALM_ORDER_COMPONENT_E-BASE_UOM_ISO
       IMPORTING
            SAP_CODE  =
       RESBD-EINHEIT
       EXCEPTIONS
            NOT_FOUND = 1
            OTHERS    = 2.
  IF SY-SUBRC <> 0.
    MESSAGE A548(B1) WITH
    BAPI_ALM_ORDER_COMPONENT_E-BASE_UOM_ISO
    'BASE_UOM_ISO                  '
    RAISING ERROR_CONVERTING_ISO_CODE.
  ENDIF.
ENDIF.

* <BAPI_FIELD>|ORIGINAL_UOM_ISO
* <SAP_FIELD>|EINHEIT
* <CODE_PART>|ISO_INT_UNIT
* <ADD_FIELD>|ORIGINAL_UOM
IF NOT BAPI_ALM_ORDER_COMPONENT_E-ORIGINAL_UOM
IS INITIAL.
  MOVE BAPI_ALM_ORDER_COMPONENT_E-ORIGINAL_UOM
    TO RESBD-EINHEIT                                                .
ELSEIF BAPI_ALM_ORDER_COMPONENT_E-ORIGINAL_UOM_ISO
IS INITIAL.
  CLEAR RESBD-EINHEIT                                                .
ELSE.
  CALL FUNCTION 'UNIT_OF_MEASURE_ISO_TO_SAP'
       EXPORTING
            ISO_CODE  =
       BAPI_ALM_ORDER_COMPONENT_E-ORIGINAL_UOM_ISO
       IMPORTING
            SAP_CODE  =
       RESBD-EINHEIT
       EXCEPTIONS
            NOT_FOUND = 1
            OTHERS    = 2.
  IF SY-SUBRC <> 0.
    MESSAGE A548(B1) WITH
    BAPI_ALM_ORDER_COMPONENT_E-ORIGINAL_UOM_ISO
    'ORIGINAL_UOM_ISO              '
    RAISING ERROR_CONVERTING_ISO_CODE.
  ENDIF.
ENDIF.

* <BAPI_FIELD>|REQUIREMENT_QUANTITY_UNIT_ISO
* <SAP_FIELD>|EINHEIT
* <CODE_PART>|ISO_INT_UNIT
* <ADD_FIELD>|REQUIREMENT_QUANTITY_UNIT
IF NOT BAPI_ALM_ORDER_COMPONENT_E-REQUIREMENT_QUANTITY_UNIT
IS INITIAL.
  MOVE BAPI_ALM_ORDER_COMPONENT_E-REQUIREMENT_QUANTITY_UNIT
    TO RESBD-EINHEIT                                                .
ELSEIF BAPI_ALM_ORDER_COMPONENT_E-REQUIREMENT_QUANTITY_UNIT_ISO
IS INITIAL.
  CLEAR RESBD-EINHEIT                                                .
ELSE.
  CALL FUNCTION 'UNIT_OF_MEASURE_ISO_TO_SAP'
       EXPORTING
            ISO_CODE  =
       BAPI_ALM_ORDER_COMPONENT_E-REQUIREMENT_QUANTITY_UNIT_ISO
       IMPORTING
            SAP_CODE  =
       RESBD-EINHEIT
       EXCEPTIONS
            NOT_FOUND = 1
            OTHERS    = 2.
  IF SY-SUBRC <> 0.
    MESSAGE A548(B1) WITH
    BAPI_ALM_ORDER_COMPONENT_E-REQUIREMENT_QUANTITY_UNIT_ISO
    'REQUIREMENT_QUANTITY_UNIT_ISO '
    RAISING ERROR_CONVERTING_ISO_CODE.
  ENDIF.
ENDIF.

* <BAPI_FIELD>|RELATIONSHIP_UNIT_ISO
* <SAP_FIELD>|ZEINH
* <CODE_PART>|ISO_INT_UNIT
* <ADD_FIELD>|RELATIONSHIP_UNIT
IF NOT BAPI_ALM_ORDER_COMPONENT_E-RELATIONSHIP_UNIT
IS INITIAL.
  MOVE BAPI_ALM_ORDER_COMPONENT_E-RELATIONSHIP_UNIT
    TO RESBD-ZEINH                                                  .
ELSEIF BAPI_ALM_ORDER_COMPONENT_E-RELATIONSHIP_UNIT_ISO
IS INITIAL.
  CLEAR RESBD-ZEINH                                                  .
ELSE.
  CALL FUNCTION 'UNIT_OF_MEASURE_ISO_TO_SAP'
       EXPORTING
            ISO_CODE  =
       BAPI_ALM_ORDER_COMPONENT_E-RELATIONSHIP_UNIT_ISO
       IMPORTING
            SAP_CODE  =
       RESBD-ZEINH
       EXCEPTIONS
            NOT_FOUND = 1
            OTHERS    = 2.
  IF SY-SUBRC <> 0.
    MESSAGE A548(B1) WITH
    BAPI_ALM_ORDER_COMPONENT_E-RELATIONSHIP_UNIT_ISO
    'RELATIONSHIP_UNIT_ISO         '
    RAISING ERROR_CONVERTING_ISO_CODE.
  ENDIF.
ENDIF.

* <BAPI_FIELD>|VSI_SIZE_UNIT_ISO
* <SAP_FIELD>|ROMEI
* <CODE_PART>|ISO_INT_UNIT
* <ADD_FIELD>|VSI_SIZE_UNIT
IF NOT BAPI_ALM_ORDER_COMPONENT_E-VSI_SIZE_UNIT
IS INITIAL.
  MOVE BAPI_ALM_ORDER_COMPONENT_E-VSI_SIZE_UNIT
    TO RESBD-ROMEI                                                  .
ELSEIF BAPI_ALM_ORDER_COMPONENT_E-VSI_SIZE_UNIT_ISO
IS INITIAL.
  CLEAR RESBD-ROMEI                                                  .
ELSE.
  CALL FUNCTION 'UNIT_OF_MEASURE_ISO_TO_SAP'
       EXPORTING
            ISO_CODE  =
       BAPI_ALM_ORDER_COMPONENT_E-VSI_SIZE_UNIT_ISO
       IMPORTING
            SAP_CODE  =
       RESBD-ROMEI
       EXCEPTIONS
            NOT_FOUND = 1
            OTHERS    = 2.
  IF SY-SUBRC <> 0.
    MESSAGE A548(B1) WITH
    BAPI_ALM_ORDER_COMPONENT_E-VSI_SIZE_UNIT_ISO
    'VSI_SIZE_UNIT_ISO             '
    RAISING ERROR_CONVERTING_ISO_CODE.
  ENDIF.
ENDIF.

* <BAPI_FIELD>|VAR_SIZE_COMP_MEASURE_UNIT_ISO
* <SAP_FIELD>|ROKME
* <CODE_PART>|ISO_INT_UNIT
* <ADD_FIELD>|VAR_SIZE_COMP_MEASURE_UNIT
IF NOT BAPI_ALM_ORDER_COMPONENT_E-VAR_SIZE_COMP_MEASURE_UNIT
IS INITIAL.
  MOVE BAPI_ALM_ORDER_COMPONENT_E-VAR_SIZE_COMP_MEASURE_UNIT
    TO RESBD-ROKME                                                  .
ELSEIF BAPI_ALM_ORDER_COMPONENT_E-VAR_SIZE_COMP_MEASURE_UNIT_ISO
IS INITIAL.
  CLEAR RESBD-ROKME                                                  .
ELSE.
  CALL FUNCTION 'UNIT_OF_MEASURE_ISO_TO_SAP'
       EXPORTING
            ISO_CODE  =
       BAPI_ALM_ORDER_COMPONENT_E-VAR_SIZE_COMP_MEASURE_UNIT_ISO
       IMPORTING
            SAP_CODE  =
       RESBD-ROKME
       EXCEPTIONS
            NOT_FOUND = 1
            OTHERS    = 2.
  IF SY-SUBRC <> 0.
    MESSAGE A548(B1) WITH
    BAPI_ALM_ORDER_COMPONENT_E-VAR_SIZE_COMP_MEASURE_UNIT_ISO
    'VAR_SIZE_COMP_MEASURE_UNIT_ISO'
    RAISING ERROR_CONVERTING_ISO_CODE.
  ENDIF.
ENDIF.

PERFORM MAP2I_BAPI_ALM_ORDER_COMPONENT
  USING
    BAPI_ALM_ORDER_COMPONENT_E
  CHANGING
    RESBD                         .





ENDFUNCTION.

FORM MAP2I_BAPI_ALM_ORDER_COMPONENT
  USING
    BAPI_ALM_ORDER_COMPONENT_E
    STRUCTURE BAPI_ALM_ORDER_COMPONENT_E
  CHANGING
    RESBD
    STRUCTURE RESBD                         .

ENDFORM.
